DROP TABLE IF EXISTS telco_churn;

CREATE TABLE telco_churn (
    customer_id VARCHAR(20) PRIMARY KEY,
    gender VARCHAR(10),
    senior_citizen INTEGER,
    partner VARCHAR(5),
    dependents VARCHAR(5),
    tenure INTEGER,
    phone_service VARCHAR(20),
    multiple_lines VARCHAR(30),
    internet_service VARCHAR(30),
    online_security VARCHAR(30),
    online_backup VARCHAR(30),
    device_protection VARCHAR(30),
    tech_support VARCHAR(30),
    streaming_tv VARCHAR(30),
    streaming_movies VARCHAR(30),
    contract VARCHAR(30),
    paperless_billing VARCHAR(5),
    payment_method VARCHAR(50),
    monthly_charges NUMERIC(10,2),
    total_charges NUMERIC(12,2),
    churn VARCHAR(5),
    churn_flag INTEGER,
    tenure_group VARCHAR(30),
    monthly_charge_band VARCHAR(30),
    customer_value_segment VARCHAR(30),
    service_count INTEGER,
    engagement_segment VARCHAR(30),
    high_risk_flag INTEGER,
    monthly_revenue_at_risk NUMERIC(12,2),
    customer_value_lost NUMERIC(12,2)
);